[2023-04-13T20:29:46.389+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.inject_data_Odesa manual__2023-04-13T20:29:34.713243+00:00 [queued]>
[2023-04-13T20:29:46.443+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.inject_data_Odesa manual__2023-04-13T20:29:34.713243+00:00 [queued]>
[2023-04-13T20:29:46.446+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T20:29:46.448+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T20:29:46.453+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T20:29:46.569+0000] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): inject_data_Odesa> on 2023-04-13 20:29:34.713243+00:00
[2023-04-13T20:29:46.609+0000] {standard_task_runner.py:55} INFO - Started process 7035 to run task
[2023-04-13T20:29:46.635+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'inject_data_Odesa', 'manual__2023-04-13T20:29:34.713243+00:00', '--job-id', '344', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp26ntffps']
[2023-04-13T20:29:46.639+0000] {standard_task_runner.py:83} INFO - Job 344: Subtask inject_data_Odesa
[2023-04-13T20:29:46.989+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.inject_data_Odesa manual__2023-04-13T20:29:34.713243+00:00 [running]> on host ffea11fb791c
[2023-04-13T20:29:47.562+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=inject_data_Odesa
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T20:29:34.713243+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T20:29:34.713243+00:00
[2023-04-13T20:29:47.566+0000] {sql.py:254} INFO - Executing: 
                INSERT INTO measures_ext (city, timestamp, temp, humidity, cloudiness, wind_speed) VALUES
                    ("Odesa",
                    1681417720,
                    283.15,
                    79,
                    "scattered clouds",
                    3.22);
            
[2023-04-13T20:29:47.589+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T20:29:48.410+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T20:29:48.422+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO measures_ext (city, timestamp, temp, humidity, cloudiness, wind_speed) VALUES
                    ("Odesa",
                    1681417720,
                    283.15,
                    79,
                    "scattered clouds",
                    3.22);
            , parameters: None
[2023-04-13T20:29:48.441+0000] {sql.py:384} INFO - Rows affected: 1
[2023-04-13T20:29:48.475+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=inject_data_Odesa, execution_date=20230413T202934, start_date=20230413T202946, end_date=20230413T202948
[2023-04-13T20:29:48.578+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-13T20:29:48.615+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
