[2023-04-13T20:28:23.670+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.inject_data_Kyiv manual__2023-04-13T20:28:06.904299+00:00 [queued]>
[2023-04-13T20:28:23.715+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.inject_data_Kyiv manual__2023-04-13T20:28:06.904299+00:00 [queued]>
[2023-04-13T20:28:23.723+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T20:28:23.739+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T20:28:23.745+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T20:28:23.791+0000] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): inject_data_Kyiv> on 2023-04-13 20:28:06.904299+00:00
[2023-04-13T20:28:23.813+0000] {standard_task_runner.py:55} INFO - Started process 6969 to run task
[2023-04-13T20:28:23.826+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'inject_data_Kyiv', 'manual__2023-04-13T20:28:06.904299+00:00', '--job-id', '327', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmppq9nksuh']
[2023-04-13T20:28:23.830+0000] {standard_task_runner.py:83} INFO - Job 327: Subtask inject_data_Kyiv
[2023-04-13T20:28:24.042+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.inject_data_Kyiv manual__2023-04-13T20:28:06.904299+00:00 [running]> on host ffea11fb791c
[2023-04-13T20:28:24.315+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=inject_data_Kyiv
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T20:28:06.904299+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T20:28:06.904299+00:00
[2023-04-13T20:28:24.317+0000] {sql.py:254} INFO - Executing: 
                INSERT INTO measures_ext (city, timestamp, temp, humidity, cloudiness, wind_speed) VALUES
                    ("Kyiv",
                    1681417079,
                    283.32,
                    83,
                    "overcast clouds",
                    2.68);
            
[2023-04-13T20:28:24.339+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T20:28:24.756+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T20:28:24.762+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO measures_ext (city, timestamp, temp, humidity, cloudiness, wind_speed) VALUES
                    ("Kyiv",
                    1681417079,
                    283.32,
                    83,
                    "overcast clouds",
                    2.68);
            , parameters: None
[2023-04-13T20:28:24.782+0000] {sql.py:384} INFO - Rows affected: 1
[2023-04-13T20:28:24.815+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=inject_data_Kyiv, execution_date=20230413T202806, start_date=20230413T202823, end_date=20230413T202824
[2023-04-13T20:28:24.874+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-13T20:28:24.931+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
