[2023-04-13T15:34:07.701+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.choose_endpoint manual__2023-04-13T15:34:05.991393+00:00 [queued]>
[2023-04-13T15:34:07.708+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.choose_endpoint manual__2023-04-13T15:34:05.991393+00:00 [queued]>
[2023-04-13T15:34:07.709+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T15:34:07.710+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T15:34:07.711+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T15:34:07.720+0000] {taskinstance.py:1309} INFO - Executing <Task(BranchPythonOperator): choose_endpoint> on 2023-04-13 15:34:05.991393+00:00
[2023-04-13T15:34:07.724+0000] {standard_task_runner.py:55} INFO - Started process 4552 to run task
[2023-04-13T15:34:07.727+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'choose_endpoint', 'manual__2023-04-13T15:34:05.991393+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpk__orff7']
[2023-04-13T15:34:07.728+0000] {standard_task_runner.py:83} INFO - Job 189: Subtask choose_endpoint
[2023-04-13T15:34:07.774+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.choose_endpoint manual__2023-04-13T15:34:05.991393+00:00 [running]> on host ffea11fb791c
[2023-04-13T15:34:07.819+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=choose_endpoint
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T15:34:05.991393+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T15:34:05.991393+00:00
[2023-04-13T15:34:07.822+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-04-13T15:34:07.822+0000] {logging_mixin.py:137} INFO - 2023-04-13T15:34:05.991393+00:00
[2023-04-13T15:34:07.823+0000] {logging_mixin.py:137} INFO - 2023-04-13 15:34:07.823808
[2023-04-13T15:34:07.828+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 210, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_dag.py", line 36, in choosing_endpoint
    if strptime('scheduled_date_to_run[:10]', 'YYYY-MM-DD') == datetime.today():
  File "/usr/local/lib/python3.7/_strptime.py", line 571, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data 'scheduled_date_to_run[:10]' does not match format 'YYYY-MM-DD'
[2023-04-13T15:34:07.835+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=choose_endpoint, execution_date=20230413T153405, start_date=20230413T153407, end_date=20230413T153407
[2023-04-13T15:34:07.842+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 189 for task choose_endpoint (time data 'scheduled_date_to_run[:10]' does not match format 'YYYY-MM-DD'; 4552)
[2023-04-13T15:34:07.859+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T15:34:07.882+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
