[2023-04-14T03:39:14.368+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.retrieve_weather_data_Lviv scheduled__2023-04-14T02:00:00+00:00 [queued]>
[2023-04-14T03:39:14.412+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.retrieve_weather_data_Lviv scheduled__2023-04-14T02:00:00+00:00 [queued]>
[2023-04-14T03:39:14.414+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T03:39:14.415+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-14T03:39:14.417+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T03:39:14.456+0000] {taskinstance.py:1309} INFO - Executing <Task(SimpleHttpOperator): retrieve_weather_data_Lviv> on 2023-04-14 02:00:00+00:00
[2023-04-14T03:39:14.478+0000] {standard_task_runner.py:55} INFO - Started process 7542 to run task
[2023-04-14T03:39:14.498+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'retrieve_weather_data_Lviv', 'scheduled__2023-04-14T02:00:00+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpe1o_v1ce']
[2023-04-14T03:39:14.501+0000] {standard_task_runner.py:83} INFO - Job 447: Subtask retrieve_weather_data_Lviv
[2023-04-14T03:39:14.801+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.retrieve_weather_data_Lviv scheduled__2023-04-14T02:00:00+00:00 [running]> on host ffea11fb791c
[2023-04-14T03:39:15.091+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=retrieve_weather_data_Lviv
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T02:00:00+00:00
[2023-04-14T03:39:15.095+0000] {http.py:123} INFO - Calling HTTP method
[2023-04-14T03:39:15.118+0000] {base.py:73} INFO - Using connection ID 'weather_http_api' for task execution.
[2023-04-14T05:01:20.524+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-04-14T05:01:26.058+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 7542. PIDs of all processes in the group: [7542]
[2023-04-14T05:01:26.072+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 7542
[2023-04-14T05:01:26.079+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-04-14T05:01:26.336+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=7542, status='terminated', exitcode=0, started='03:39:14') (7542) terminated with exit code 0
